import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseFrontmatter } from "./history-entry.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const HARNESS_ROOT = join(__dirname, "..", "..");
const REPO_ROOT = join(HARNESS_ROOT, "..");
const AGENTS_MD_PATH = join(REPO_ROOT, "AGENTS.md");

export const SKILLS_OVERVIEW_BEGIN =
  "<!-- BEGIN Skills Overview (generated by harness:prep) -->";
export const SKILLS_OVERVIEW_END =
  "<!-- END Skills Overview (generated by harness:prep) -->";

const USE_CASES_FALLBACK = "Review the skill before executing related work.";

function extractUseCases(body) {
  if (!body || !body.trim()) return [];

  const lines = body.split("\n");
  const useCases = [];
  let inUseCases = false;
  let sawBullet = false;

  for (const line of lines) {
    const anyHeading = line.match(/^#{1,6}\s+(.+?)\s*$/);
    const heading = line.match(/^##\s+(.+?)\s*$/);
    if (heading) {
      const value = heading[1].trim().toLowerCase();
      if (value === "use cases" || value === "when to use") {
        inUseCases = true;
        continue;
      }
      if (inUseCases) break;
      continue;
    }

    if (inUseCases && anyHeading) break;
    if (!inUseCases) continue;

    const bullet = line.match(/^\s*[-*]\s+(.+?)\s*$/);
    if (bullet) {
      const value = bullet[1].replace(/\s+/g, " ").trim();
      if (value) {
        useCases.push(value);
        sawBullet = true;
      }
      continue;
    }

    if (!line.trim()) continue;
    if (sawBullet) break;
  }

  return useCases;
}

export function loadSkillPrompt(skillId) {
  const skillPath = join(REPO_ROOT, "workflows", "skills", skillId, "SKILL.md");

  if (!existsSync(skillPath)) {
    throw new Error(
      `Skill not found: ${skillId}\nExpected: workflows/skills/${skillId}/SKILL.md`,
    );
  }

  const content = readFileSync(skillPath, "utf-8");
  const { data, body } = parseFrontmatter(content);

  if (!body || !body.trim()) {
    throw new Error(`Skill has no prompt body: ${skillId}`);
  }
  if (!data?.id) {
    throw new Error(`Skill missing 'id' in frontmatter: ${skillId}`);
  }
  if (!data?.summary) {
    throw new Error(`Skill missing 'summary' in frontmatter: ${skillId}`);
  }

  return body.trim();
}

export function getSkillMeta(skillId) {
  const skillPath = join(REPO_ROOT, "workflows", "skills", skillId, "SKILL.md");
  if (!existsSync(skillPath)) {
    throw new Error(`Skill not found: ${skillId}`);
  }

  const content = readFileSync(skillPath, "utf-8");
  const { data, body } = parseFrontmatter(content);
  return {
    id: data?.id || skillId,
    summary: data?.summary || "",
    useCases: extractUseCases(body),
  };
}

export function listSkillMeta() {
  const skillsDir = join(REPO_ROOT, "workflows", "skills");
  if (!existsSync(skillsDir)) return [];

  const entries = readdirSync(skillsDir, { withFileTypes: true });
  const skills = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const skillPath = join(skillsDir, entry.name, "SKILL.md");
    if (!existsSync(skillPath)) continue;

    const content = readFileSync(skillPath, "utf-8");
    const { data, body } = parseFrontmatter(content);
    skills.push({
      id: data?.id || entry.name,
      summary: data?.summary || "",
      useCases: extractUseCases(body),
    });
  }

  return skills.sort((a, b) => a.id.localeCompare(b.id));
}

export function renderSkillsOverviewBlock(skills) {
  const lines = [
    SKILLS_OVERVIEW_BEGIN,
    "",
    "## Skills Overview",
    "",
    "- Skills are reusable workflow playbooks stored in `workflows/skills/`.",
    "- The canonical writer for this block is `npm run harness:prep`; do not edit it manually.",
    "- The canonical content source for this block is repo-local skills under `workflows/skills/`.",
    "- This index describes available skills only; it does not widen permissions or override repo or skill-local guardrails.",
    "- If your task overlaps any `USE WHEN` case below, open that skill's `SKILL.md` before you act.",
    "- See `workflows/skills/` for full skill instructions.",
    "",
  ];

  if (!skills || skills.length === 0) {
    lines.push("- No repo skills found under `workflows/skills/`.");
  } else {
    for (const skill of skills) {
      const useWhen =
        skill.useCases && skill.useCases.length > 0
          ? skill.useCases.join(" | ")
          : USE_CASES_FALLBACK;
      lines.push(`- \`${skill.id}\`: ${skill.summary} USE WHEN: ${useWhen}`);
    }
  }

  lines.push("", SKILLS_OVERVIEW_END);
  return lines.join("\n");
}

function splitAgentsContent(content) {
  const hasBegin = content.includes(SKILLS_OVERVIEW_BEGIN);
  const hasEnd = content.includes(SKILLS_OVERVIEW_END);

  if (!hasBegin && !hasEnd) {
    return { base: content.replace(/\s*$/, "") };
  }

  if (hasBegin && hasEnd) {
    const start = content.indexOf(SKILLS_OVERVIEW_BEGIN);
    const end = content.indexOf(SKILLS_OVERVIEW_END, start);
    const tailStart = end + SKILLS_OVERVIEW_END.length;
    return {
      base: (content.slice(0, start) + content.slice(tailStart)).replace(
        /\s*$/,
        "",
      ),
    };
  }

  const markerIndex = hasBegin
    ? content.indexOf(SKILLS_OVERVIEW_BEGIN)
    : content.indexOf(SKILLS_OVERVIEW_END);
  return { base: content.slice(0, markerIndex).replace(/\s*$/, "") };
}

export function buildAgentsWithSkillsOverview(content, skills) {
  const { base } = splitAgentsContent(content);
  return `${base}\n\n${renderSkillsOverviewBlock(skills)}\n`;
}

export function syncAgentsSkillsOverview() {
  if (!existsSync(AGENTS_MD_PATH)) {
    throw new Error(`AGENTS.md not found at ${AGENTS_MD_PATH}`);
  }

  const skills = listSkillMeta();
  const current = readFileSync(AGENTS_MD_PATH, "utf-8");
  const next = buildAgentsWithSkillsOverview(current, skills);

  if (current !== next) {
    writeFileSync(AGENTS_MD_PATH, next, "utf-8");
    return { changed: true };
  }

  return { changed: false };
}
